version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      - mlflow
    networks:
      - mlops_network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000
      MLFLOW_BACKEND_STORE_URI: sqlite:///mlflow_data/mlflow.db
      MLFLOW_DEFAULT_ARTIFACT_ROOT: /mlflow_data/artifacts
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow_data/mlflow.db
      --default-artifact-root /mlflow_data/artifacts
      --host 0.0.0.0
      --port 5000
    volumes:
      - ./mlflow_data:/mlflow_data
    networks:
      - mlops_network

  tests:
    build:
      context: .
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    command: ["pytest", "--disable-warnings", "tests/"]
    networks:
      - mlops_network

networks:
  mlops_network:
    driver: bridge